### ISSUE TITLE
Play by play base data?

### ISSUE THREAD

**Issue by RSABryan** [localpcguy/nflgamestats#1]
Hi guys, I've fooled around with a bunch of variations of the sample code in order to pull base play by play data...

First off, here's what I'm looking for.  This is from a sample play by play dataset I downloaded for 2014:

![2015-09-22 04_09_45-cortana](https://cloud.githubusercontent.com/assets/14686110/10013480/cfc4655c-60df-11e5-9e7e-81fba259e4dd.jpg)

When I try:

game1 = nflgame.games(2015, week=1)
game1.csv("w1.csv")

I get, "AttributeError: 'list' object has no attribute 'csv'", ok so that makes sense.

Then I try the more direct route:
nflgame.games(2015, week=1).csv("w1.csv")

Same error, different tune...

When I try with the combine statement I get a nice file that has stats for each player, again I'm looking for the more granular play by play data.

Any thoughts here guys and gals?

Thanks
RSABryan

**Comment by localpcguy** [comment]
Guessing you want the Python project that inspired this repo? Sorry I can't be much help with your request.

http://blog.burntsushi.net/nfl-live-statistics-with-python/
